# Intro a NumPy

## Strutture dati in Python
* variabili
* tuple
* list
* dict
* array

### Variabili

In [1]:
# in Python gli oggetti sono tipizzati ma i tipi non sono dichiarati
stringa = "ciao"
num_str = str('10')
num = 5

In [2]:
# infatti durante le operazioni questi tipi vengono verificati
num_str + num

TypeError: must be str, not int

## Tuple

In [3]:
# le tuple sono insiemi di variabili, anche eterogenee
tupla_1 = (1, 'uno', 1.0)
tupla_1

(1, 'uno', 1.0)

In [4]:
# le tuple non sono modificabili e sono perfette come valori di ritorno
def make_tuple(a, b, c):
    return (a+1, str(b)+"__", c**c)

make_tuple(1, 'uno', 3.14)

(2, 'uno__', 36.33783888017471)

## List

In [5]:
# le liste sono sicuramente le strutture dati piu' usate
list_1 = [1,2,3,4]
list_1

[1, 2, 3, 4]

In [6]:
# sono indicizzate e modificabili, partendo da 0
list_1[2] = 30
list_1

[1, 2, 30, 4]

In [10]:
# le liste sono contenitori eterogeneii
lista_spesa = [ (1, 'tonno'), (5, 'mele'), (3.5, 'etti di carne') ]
lista_spesa[1]

(5, 'mele')

In [11]:
# gli indici sono flessibili
lista_spesa[-1]

(3.5, 'etti di carne')

In [12]:
# dall'indice 1 incluso al 3 escluso
lista_spesa[1:3]

[(5, 'mele'), (3.5, 'etti di carne')]

## Dict

In [15]:
# i dizionari sono delle mappe chiave valore
dizionario = {"uno": 1.0, "due": 2.0, "tre": 3.0}
dizionario['due'] 
dizionario['444'] = 4.0
dizionario.items()

dict_items([('uno', 1.0), ('due', 2.0), ('tre', 3.0), ('444', 4.0)])

## Array
https://docs.python.org/3.6/library/array.html

In [16]:
# array e' una sequenza di tipi primitivi omogenea, di piu' basso livello rispetto a list
from array import array
# 'l' sta per intero senza segno (vedi tabella nella doc)
arr = array('l', [1, 2, 3, 4, 5])
arr

array('l', [1, 2, 3, 4, 5])

In [17]:
arr.append(6)
arr[-1]

6

In [18]:
arr.append("7")

TypeError: an integer is required (got type str)

# NumPy
Vettori multidimensionali

In [19]:
# la convenzione
import numpy as np

In [20]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [21]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [24]:
np.arange(5) + 1 

array([1, 2, 3, 4, 5])

In [26]:
np.arange(5) + np.ones(5)

array([1., 2., 3., 4., 5.])

## Matrici

In [27]:
# 1 dim
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# 2 dim
np.arange(12).reshape(2,-1) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
# 3 dim
np.arange(12).reshape((2, 3, -1))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

## Indici

In [30]:
vect = np.arange(12).reshape((2, 3, -1))

In [31]:
vect[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
vect[0,1]

array([2, 3])

In [34]:
vect[0,1,1]

3

In [35]:
#[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
line = np.arange(10,20)
indx = [1,3,5]
line[indx]

array([11, 13, 15])

In [36]:
combinazioni = np.array([
    [0,0,0],
    [1,0,0],
    [0,1,0],
    [0,0,1],
])
scelte = np.array([
    [0,1],
    [2,3]
])
combinazioni[scelte]

array([[[0, 0, 0],
        [1, 0, 0]],

       [[0, 1, 0],
        [0, 0, 1]]])

## Maschere

In [37]:
vect = np.arange(8)

In [38]:
pari = vect%2 == 0
pari

array([ True, False,  True, False,  True, False,  True, False])

In [39]:
dispari = ~pari
dispari

array([False,  True, False,  True, False,  True, False,  True])

In [40]:
vect[dispari]

array([1, 3, 5, 7])

## Operazioni

In [41]:
rg = np.random.default_rng(1)
tabellone = rg.random((1000,1000))
tabellone.shape

(1000, 1000)

In [42]:
tabellone[100,100]

0.9646722103138076

In [43]:
# remember: no for loop!
tab_sin = np.sin(tabellone) * 100
tab_sin[10:15, 10:15]

array([[37.53340799, 19.48878668, 70.81411574,  5.34161961, 65.56816237],
       [70.78193449, 27.25544945, 49.36273104, 58.43269833, 47.27355616],
       [78.09655655, 57.06861549, 44.42274159, 69.79370635, 80.85967781],
       [56.73496676, 35.12566524, 38.73326575,  7.12311146, 69.46902214],
       [48.66615077, 54.44557383,  4.49580625, 78.36746532, 83.49673521]])